homepage:
  image: ghcr.io/gethomepage/homepage:latest
  container_name: homepage
  logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 1m
  volumes:
    - /docker/homepage/config:/app/config
    - /var/run/docker.sock:/var/run/docker.sock:ro # pass local proxy
  ports:
    - 3000:3000
  restart: unless-stopped
  network_mode: DockerInternal
